version: "3"
services:
  web:
    image: nginx:1-alpine
    volumes:
      - ./.docker-compose.d/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - sails
  sails:
    build:
      context: .
      dockerfile: ./.docker-compose.d/Dockerfile-sails
    command: ./.docker-compose.d/start.sh
    ports:
      - "1337:1337"
    volumes:
      - .:/home/scumizu/sails
      - /home/scumizu/sails/node_modules/
      - ./.pm2:/home/scumizu/.pm2
    links:
      - db
      - redis
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: "scumizu"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: redis:3-alpine
